ManageIQ/manageiq-providers-nuage

app/models/manageiq/providers/nuage/network_manager.rb
manageiq-providers-nuage.gemspec

Without this gem I was getting error about the missing Excon constant while trying to log into Nuage provider. This patch adds the same version as the one currently used in OpenStack provider.

Add the missing excon gem

---

spec/factories/ext_management_system.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
spec/spec_helper.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml

The Nuage network manager did previously not provide anky kind of automated tests causing refactoring and implementation of additional features rather risky (and time consuming). This patch introduces the initial spec that uses VCR recordings against a testing VSD environment. The spec currently only verifies the table counts as the refresh parser does not populate much data into the database.
The patch obfuscates the actual Nuage backend (hostname, username/password).
@miq-bot add_label refactoring

Introduce VCR tests for Nuage network manager

---

app/models/manageiq/providers/nuage/manager_mixin.rb
app/models/manageiq/providers/nuage/network_manager.rb

Currently, the network manager code contained everything in one place, unlike many of the other manageiq providers. Since we are going to be extending this part with the events, this patch moves most of the logic targeting towards the backend Nuage services into a separate mixin to keep the main manager code clean.

Move backend manager logic into a mixin

---

app/models/manageiq/providers/nuage/network_manager/refresh_parser.rb
config/settings.yml
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb

This commit is a preparation to be able to support graph inventory refresh with the next commit. Basically we provide unit tests for refresh parser so that we'll be able to assure that the new graph inventory refresh works identically to the current (legacy) one.
Writing tests we've also discovered that there is a bug in current parser - the network groups were not associated correctly with the security groups. Fixed. God bless the unit tests! :D
/cc @gberginc

Provide extensive unit tests for legacy refresher

---

app/models/manageiq/providers/nuage/builder.rb
app/models/manageiq/providers/nuage/inventory.rb
app/models/manageiq/providers/nuage/inventory/collector.rb
app/models/manageiq/providers/nuage/inventory/collector/network_manager.rb
app/models/manageiq/providers/nuage/inventory/parser.rb
app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
app/models/manageiq/providers/nuage/inventory/persister.rb
app/models/manageiq/providers/nuage/inventory/persister/network_manager.rb
app/models/manageiq/providers/nuage/inventory_collection_default/network_manager.rb
app/models/manageiq/providers/nuage/network_manager.rb
app/models/manageiq/providers/nuage/network_manager/refresher.rb
config/settings.yml
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb

With this commit we implement whatever is needed for the fancy new graph inventory refresh to step in. For now we keep legacy refresher also in place (switchable in settings.yml), but the plan is to migrate to the new refresher completely.
Exactly same unit tests that were passing for legacy refresher are now passing for both the legacy refresher and the new graph refresher.
Depends on: https://github.com/ManageIQ/manageiq-providers-nuage/pull/12
Depends on: https://github.com/ManageIQ/manageiq/pull/16136
/cc @gberginc

Implement graph inventory refresh for network manager

---

app/models/manageiq/providers/nuage/inventory_collection_default/network_manager.rb

Now that `ManagerRefresh::InventoryCollectionDefault::NetworkManager` in miq master has the function `network_groups` upstreamed, we can remove the local implementation here in Nuage provider, as suggested by TODO.
@miq-bot assign @Ladas 

Depend on miq core instead having own function

---

app/models/manageiq/providers/nuage/network_manager/refresher.rb

Recently the ManagerRefresher was introduced in the core repository. By extending it, we cleanup our Nuage::NetworkManager::Refresher so that it no longer implements the two copy-pasted functions:
- collect_inventory_for_targets
- parse_targeted_inventory
@miq-bot assign @Ladas 
@miq-bot add_label refactoring

Let Refresher extend the new ManagerRefresher

---

.travis.yml
bin/qpid_install.sh
manageiq-providers-nuage.gemspec
spec/models/manageiq/providers/nuage/network_manager_spec.rb

The worker used by Travis does not have the most current version of the Qpid Proton installed, so we need to manually install it from source. This patch also adds a simple spec that chects that Qpid gem is properly installed.

Install qpid_proton for Travis

---

.travis.yml
bin/qpid_install.sh

Because qpid-proton needs to be built from source, additional system
packages are needed (installed with sudo rights). This caused that the
vendor bundle is created by the root user and resulted in Bundler not
being able to install other gems.
This patch now removes the use of sudo to the bare minimum, namely
installing the packages required to build qpid-proton from source.

Fix Qpid proton Travis build

---

bin/qpid_install.sh

With this commit we make sure that qpid source is cloned at appropriate tag. For some reason the tag name is "0.18.0-rc1" which suggests that it's only a release candidate, but since version 0.19.0 is already out, we're quite certain that this tag actually points to the final implementation of 0.18.0.
---
EXPLANATION: It is most amusing that it happened yesterday only **two hours** after the qpid_install.sh was [merged](https://github.com/ManageIQ/manageiq-providers-nuage/pull/19) that the qpid 0.19.0 was released and only then they provided [tags for 0.18.0](https://github.com/apache/qpid-proton/tags). Therefore we were unable to specify the tag earlier.
---
We're sorry for all the confusion regarding qpid installation, hopefully this PR will eventually bring peace 😃 
@miq-bot add_label …

Lock qpid version to 0.18.0

---

app/models/manageiq/providers/nuage/builder.rb
app/models/manageiq/providers/nuage/inventory/collector.rb
app/models/manageiq/providers/nuage/inventory/collector/network_manager.rb
app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
app/models/manageiq/providers/nuage/inventory/persister.rb
app/models/manageiq/providers/nuage/inventory/persister/target_collection.rb
app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
config/settings.yml
spec/factories/cloud_subnet.rb
spec/factories/network_group.rb
spec/factories/security_group.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_subnet.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_subnet_is_deleted.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_subnet_is_updated.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_group.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_group_is_deleted.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_group_is_updated.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/security_group.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/security_group_is_deleted.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/security_group_is_updated.yml

With this commit we implement targeted refresh for NetworkManager. Following targets are supported, together with inferred co-targets:
```
TARGET           INFERS
-----------------------------------------------
NetworkGroup  -> cloud_subnets, security_groups
SecurityGroup -> network_group
CloudSubnet   -> network_group, security_groups
```
Read the table above like this: "When targeted refresh for NetworkGroup is triggered, also corresponding CloudSubnets and SecurityGroups get updated"... All three cases are tested in targeted_refresh_spec.rb.
To implement targeted refresh we had to slightly modify the existing parser so that we are able to share it for both graph refresh and targeted refresh.
@miq-bot assign @Ladas 
/cc @gberginc @gasper-vrhovsek

Implement targeted refresh for NetworkManager

---

.travis.yml
bin/qpid_install.sh

Previously, the gem was installed directly from the source. However,
since the `qpid_proton` gem has been incorporated as optional in the
core `Gemfile` it is now also possible to use that gem directly by
setting the environment variable `BUNDLE_WITH=qpid_proton`.
This patch updates Travis to use the gem from `Gemfile`.

Install qpid_proton gem from core Gemfile

---

app/models/manageiq/providers/nuage/manager_mixin.rb
app/models/manageiq/providers/nuage/network_manager.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher/messaging_handler.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher/runner.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher/stream.rb
app/models/manageiq/providers/nuage/network_manager/event_parser.rb
config/settings.yml
spec/factories/ext_management_system.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

This commit introduces the full blown event catcher for Nuage manager based on ActiveMQ message bus. Further to default authentication, AMQP is now provided via Qpid Proton gem, along with the corresponding message handler responsible for the delivery of messages into CFME.

Introduce Nuage event catcher

---

app/models/manageiq/providers/nuage/manager_mixin.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

The UI repo has changed the way endpoint validation occurs, causing a
problem withinin the angular controller when creating the arguments for
`raw_connect`. Previously, the `auth_url` was required as an argument
which mandated the need to expose the `auth_url` from the Nuage manager
so that it could be used in the UI controller.
Instead, this patch replaces `auth_url` with the specific arguments that
are needed to build the `auth_url` so that the UI can directly pass
those values into the manager.

Update raw_connect to simplify validation from UI

---

app/models/manageiq/providers/nuage/manager_mixin.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher/messaging_handler.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

Qpid proton allows for automatic failover in case an error occurs for
the currently active connection. When the Nuage provider is associated
with endpoints with roles `amqp-fallback1` and `amqp-fallback2`, these
will be used to configure the message handler.
Video showing the behaviour of the fallback: https://youtu.be/w-AekPyMOmo.
@miq-bot add_label events

Use AMQP fallback endpoints when available

---

app/models/manageiq/providers/nuage/manager_mixin.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

Previously it was possible to pass an empty API version causing the
provider to fail. This patch updates the provider to set the default API
version to the latest version (v5_0), which is also the first one going
to be supported by this provider. Specs are updated to address this
change.
@miq-bot add_label bug

Fix Nuage api_version

---

config/settings.yml

Prior to this patch, the UI could not show the option to create new
network managers because these are typically created along with cloud
manager. Nuage is a dedicated SDN requiring ability to add the provider
manually.
The UI depends on the `product.nuage` setting to enable the network
providers which this patch adds directly into the Nuage.
@miq-bot assign @blomquisg 

Enable Nuage network manager

---

spec/models/manageiq/providers/nuage/vsd_client/vsd_client_spec.rb

This will add rspec test for corner cases expected in vsd_client that can not/should not be simulated using vcr cassettes.

Add vsd_client corner case rspec test

---

app/models/manageiq/providers/nuage/manager_mixin.rb

When provider is added the credentials validation is newly done via `raw_connect` (class method) instead of `verify_credentials` (needed EMS object). Further reading on this change can be found here: ManageIQ/manageiq-ui-classic#1580
This change ensures that exceptions are handled properly, because the `verify_credentials` is not called anymore.
Similar PRs for other providers:
- https://github.com/ManageIQ/manageiq-providers-azure/pull/161
- https://github.com/ManageIQ/manageiq-providers-hawkular/pull/100
- https://github.com/ManageIQ/manageiq-providers-scvmm/pull/41
- https://github.com/ManageIQ/manageiq-providers-google/pull/28
- https://github.com/ManageIQ/manageiq-providers-lenovo/pull/108

Fix exception handing for credential validation on raw_connect

---

app/models/manageiq/providers/nuage/manager_mixin.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

This fixes endpoint url generation from form input values. Before, if SSL was selected, the url began
with 'http'. Now when either 'SSL' or 'SSL with validation' are selected, the url begins with 'https'.
@miq-bot add_label bug
/cc @gberginc 
/cc @miha-plesko

Fix protocol selection when adding a new nuage provider

---

app/models/manageiq/providers/nuage/manager_mixin.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

This change modifies the error message returned from nuage when selecting
the wrong security protocol. The old error message was:
```
wrong status line: "\x15\x03\x03\x00\x02\x02"
``` 
which was not informative to the end user.
@miq-bot bug
/cc @miha-plesko @gberginc

Human readable error when selecting wrong security protocol

---

app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
spec/models/manageiq/providers/nuage/vsd_client/vsd_client_spec.rb

vsd_client returned nil when receiving a response with empty body.
This caused a NoMethodError when calling each on nil down the line.
Now for all 200 responses with empty bodies vsd_client will return `[]`.
The issue is described here: https://bugzilla.redhat.com/show_bug.cgi?id=1527207 
/cc @miha-plesko @gberginc 
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes, fine/yes

Return empy list instead of nil for responses with empty bodies

---

app/models/manageiq/providers/nuage/manager_mixin.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

Encode username and password to avoid errors when using special characters such as `@` inside username and/or password. Because the amqp endpoint is generated as:
`[userid]:[password]@[amqp.endpoint.url]`
When, for instance, password contained `@` it got generated as something like:
`userid:p@ssword@amqp.endpoint.url`
which caused the validate call to get stuck in an infinite loop.
@miq-bot add_label bug
/cc @gberginc @miha-plesko

Url encode Nuage credentials

---

app/models/manageiq/providers/nuage/network_manager/event_parser.rb
spec/models/manageiq/providers/nuage/network_manager/event_parser_spec.rb

With this commit we make sure that events are always created with unique ems_ref. For most of them we just grab value from the event hash, but we make up a new unique value when ID is not present in event hash to make is unique at least from this point on.
@miq-bot assign @bronaghs 
This is a replacement for https://github.com/ManageIQ/manageiq-providers-nuage/pull/52. There were two issues addressed in #52: the performance issue and the ID issue. The performance issue was solved by upgrading the underlying qpid_proton gem while the ID issue is solved by this PR.
/cc @gberginc

Assign :ems_ref to the event

---

app/models/manageiq/providers/nuage/manager_mixin.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher/messaging_handler.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher/runner.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher/stream.rb
bin/qpid_install.sh
config/settings.yml
spec/models/manageiq/providers/nuage/network_manager_spec.rb

With this commit we adjust whatever needed to support qpid_proton version 0.19.0 instead of 0.18.1. Even if only a "minor" number has increased, the API is broken hence this commit. Most notable differences in qpid_proton API are:
- username/password can no longer be provided as part of URL, but separately
- class Qpid::Proton::Handler::MessagingHandler has been replaced with Qpid::Proton::Handler::MessagingHandler
- some handler callbacks have been renamed (on_start -> on_container_start etc.)
- some other functions have been renamed and signature has been updated
- `:urls` option is no longer supported (connection to fallback endpoint had to be implemented on MIQ level)
The reason to switch to qpid_proton 0.19.0 is that we measured huge performance issues on 0.18.1 that seem to be fixed …

Upgrade qpid_proton related stuff to support v0.19.0

---

app/models/manageiq/providers/nuage/network_manager.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

With this commit we overwrite `name` method for `NetworkManager`,
since core's method uses parent's name and
Nuage's network provider has no parent.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1537547

Add name method

---

app/models/manageiq/providers/nuage/manager_mixin.rb

`stop_event_monitor_queue_on_change` is now overriden for Nuage network provider so EventCatcher restarts when AMQP endpoints or fallback endpoints or port are changed.
This commit replaces https://github.com/ManageIQ/manageiq-providers-nuage/pull/60
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1534460
Reference: https://github.com/ManageIQ/manageiq-providers-nuage/pull/60#issuecomment-359870507

Add `stop_event_monitor_queue_on_change` method

---

.rubocop_local.yml
app/models/manageiq/providers/nuage/manager_mixin.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher/stream.rb
app/models/manageiq/providers/nuage/network_manager/refresh_parser.rb
app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
app/models/manageiq/providers/nuage/network_manager/vsd_client/rest.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

With this commit we redirect all Nuage specific logs into a dedicated file (instead of general-purpose evm.log).
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1534449
Related PR in core: https://github.com/ManageIQ/manageiq/pull/16455 (already merged)
@miq-bot add_label enhancement,gaprindashvili/yes

Redirect logs into log/nuage.log file

---

app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb

We crash hard in case gateway address returned from Nuage API is `nil`. Well, not anymore.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1551015
@miq-bot add_label bug,gaprindashvili/yes
@miq-bot assign @juliancheal

Handle subnets with missing gateway/netmask

---

app/models/manageiq/providers/nuage/network_manager/event_catcher.rb
spec/factories/ext_management_system.rb
spec/models/manageiq/providers/nuage/network_manager/event_catcher_spec.rb

Nuage GUI offers option "None" for eventing (as opposed to "AMQP"). Turns out that EventCatcher restarts itself like crazy in case "None" is chosen because it tries to connect to AMQP anyway even if it lacky both endpoint information and credentials.
With this commit we make sure that EventCatcher is only run for those Nuage EMSes that have option "AMQP" actually chosen.
NOTE: the very same approach was taken for VMware vCloud provider here: https://github.com/ManageIQ/manageiq-providers-vmware/pull/199, but @agrare hasn't approved it yet. I've tested it locally and everything works as expected, so I'm looking forward to be hearing if there is a more elegant way of achieveing this, or is it OK?
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1527209
@miq-bot …

Don't run EventCatcher when user opts-in for "None"

---

config/settings.yml

With this commit we connect Nuage provider also to CNAAlarms topic and not only to CNAMessages topic, as requested by Nuage.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1554230
@miq-bot add_label enhancement,gaprindashvili/yes
/cc @gberginc

Also connect to CNAAlarms AMQP topic

---

app/models/manageiq/providers/nuage/network_manager/event_catcher/messaging_handler.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher/stream.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

Raising exceptions from within AMQP callbacks (defined in MessagingHandler) prevents qpid_proton gem from closing TCP connection properly which results in file descriptor leakage (see https://issues.apache.org/jira/browse/PROTON-1791). It's a bug in gem (sockets shouldn't leak no matter what) which will be resolved with next release (qpid_proton 0.22.0) in a month, but with this commit we avoid raising exceptions in callbacks to resolve file descriptor problem immediately.
Replacement for https://github.com/ManageIQ/manageiq-providers-nuage/pull/76
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1554771
@miq-bot assign @juliancheal
@miq-bot add_label enhancement,gaprindashvili/yes
/cc @gberginc

Don't raise exceptions from within AMQP callbacks

---

app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
spec/models/manageiq/providers/nuage/network_manager/inventory_parser_spec.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb

Turns out that Nuage allows strange things to exist in its database when modifying it through their REST API (GUI asserts certain validation, but not REST API). With this commit we take some precautions, because we don't want our refresher to be crashing in such cases.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1551015
@miq-bot add_label enhancement,gaprindashvili/yes
@miq-bot assign @juliancheal

Harden refresh parser

---

app/models/manageiq/providers/nuage/inventory/collector.rb
app/models/manageiq/providers/nuage/inventory/collector/network_manager.rb
app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
app/models/manageiq/providers/nuage/network_manager.rb
app/models/manageiq/providers/nuage/network_manager/cloud_subnet_l2.rb
app/models/manageiq/providers/nuage/network_manager/cloud_subnet_l3.rb
app/models/manageiq/providers/nuage/network_manager/cloud_tenant.rb
app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
spec/spec_helper.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml

With this commit we introduce a subclass of CloudSubnet model that represents a standalone subnet, called "L2 domain" on Nuage. Main difference is that such standalone domain is not connected to any NetworkRouter.
We're introducing `CloudSubnetL2` because it's important for Nuage that they are able to differentiate between the two (L3 subnet and L2 subnet). Hence we also introduce auxilary methods `l3_cloud_subnets` and `l2_cloud_subnets` on NetworkManager and CloudTenant model to be able to only get desired subnet type.
RFE BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1574921

Inventory L2 Domain entity (Nuage) as CloudSubnet model (MIQ)

---

app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
app/models/manageiq/providers/nuage/network_manager/vsd_client/rest.rb
spec/models/manageiq/providers/nuage/vsd_client/vsd_client_spec.rb

With this commit we modify VsdClient so that each API call is performed with default headers unless explicitly speficied differently.
Having the editor open I also updated the code in VsdClient::Rest because it contained a copy-paste of entire sections instead reusing central function...

Reset API headers after each call

---

config/settings.yml

With this commit we cleanup settings.yaml since UI no longer needs `::Settings.product.nuage` setting but rather relies on config/permissions.yaml entries.
Depends on: https://github.com/ManageIQ/manageiq-ui-classic/pull/3979
/cc @djberg96

Cleanup config/settings.yaml after changes in UI

---

app/models/manageiq/providers/nuage/inventory/collector.rb
app/models/manageiq/providers/nuage/inventory/collector/network_manager.rb
app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
app/models/manageiq/providers/nuage/inventory/persister/definitions/network_collections.rb
app/models/manageiq/providers/nuage/network_manager.rb
app/models/manageiq/providers/nuage/network_manager/network_port/bridge.rb
app/models/manageiq/providers/nuage/network_manager/network_port/container.rb
app/models/manageiq/providers/nuage/network_manager/network_port/host.rb
app/models/manageiq/providers/nuage/network_manager/network_port/vm.rb
app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml

With this commit we inventory NetworkPorts that can be of different
types in Nuage:
- Bridge vPort
- Host vPort
- VM vPort
- Container vPort
Each of them has a unique way of retrieving IP address by performing additional API request, hence the case-when statement in the parser.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1574927

Inventory vPort entities (Nuage) into NetworkPort model (MIQ)

---

app/models/manageiq/providers/nuage/network_manager/network_router.rb

With this commit we remove relation which allows NetworkRouter to relate to multiple FloatingIps directly (instead via CloudNetwork). Until https://github.com/ManageIQ/manageiq-schema/pull/217 is merged we are not able to use such direct relation or else UI crashes.

Temporarily remove many-to-many from NetworkRouter

---

app/models/manageiq/providers/nuage/network_manager.rb
app/models/manageiq/providers/nuage/network_manager/cloud_subnet/l2.rb
app/models/manageiq/providers/nuage/network_manager/cloud_subnet/l3.rb
app/models/manageiq/providers/nuage/network_manager/cloud_subnet_l2.rb
app/models/manageiq/providers/nuage/network_manager/cloud_subnet_l3.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb

With this commit we fix current strange subclassing:
```
ManageIQ::Providers::Nuage::NetworkManager::CloudSubnetL2
ManageIQ::Providers::Nuage::NetworkManager::CloudSubnetL3
```
into proper one (notice `::L2` and `::L3` at the end):
```
ManageIQ::Providers::Nuage::NetworkManager::CloudSubnet::L2
ManageIQ::Providers::Nuage::NetworkManager::CloudSubnet::L3
```

Properly subclass CloudSubnet

---

app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb
app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
spec/factories/cloud_subnet.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/l2_cloud_subnet.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/l2_cloud_subnet_is_deleted.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/l2_cloud_subnet_is_updated.yml

With this commit we adjust targeted refresh to works for both kind of subnets - CloudSubnet::L2 and CloudSubnet::L3. When we recieve event we need to pass additional information to target in order to later know what type of subnet are we updating. We need to know this because different API calls need to be used for L2 and L3 subnets...

Targeted refresh for L2 and L3 CloudSubnets

---

app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb
app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
spec/factories/network_port.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_bridge.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_container.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_host.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_is_deleted.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_is_updated.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_vm.yml

Targeted refresh for NetworkPorts

---

app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb

We're doing a lot of unneccessary caching in targeted collector. Not anymore - with this commit we simplify the code and spare memory. Rspecs are left intact and there are no errors about missing http interactions which confirms that caching was never used - because each entity is fetched and parsed only once anyway.

Reduce memoization in targeted refresh

---

app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
app/models/manageiq/providers/nuage/network_manager/network_router.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb

With this commit we make use of recently added foreign key on NetworkRouter that's pointing to FloatingIp to connect the two.
@Ladas here we are now, https://github.com/ManageIQ/manageiq-schema/pull/217 is merged and we're able to connect FloatingIp directly to the NetworkRouter, as discussed some time ago.

Relate FloatingIp to NetworkRouter

---

app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
app/models/manageiq/providers/nuage/inventory/persister/definitions/network_collections.rb

When refreshing NetworkPort we're also updating its many-to-many relation with CloudSubnet (to store address in the intermidiate table). And this fails with ugly integritiy error if subnet is not fetched yet.
With this commit the interity error by making sure subnet is also fetched together with port.

Infer related CloudSubnet in case of NetworkPort refresh

---

app/models/manageiq/providers/nuage/manager_mixin.rb
app/models/manageiq/providers/nuage/network_manager/vsd_client/rest.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb

When user forgets to pick API version upon Nuage provider creation she gets very strange error. Problem is that in such cases our Angular passes in literally value (with questionmarks and all):
```
'? string:v2 ?'
```
This is then used to compose URL and BOOOM. With this commit we therefore manually chech that version looks like expected e.g. `v5_0` and raise error otherwise with descriptive error message which is displayed to user upon credentials validation.
Before 👎 👎 👎 :
After 👍 👍 👍 :

Check for invalid api_version string

---

app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb
app/models/manageiq/providers/nuage/network_manager/cloud_tenant.rb
app/models/manageiq/providers/nuage/network_manager/network_router.rb
spec/factories/network_router.rb
spec/models/manageiq/providers/nuage/network_manager/cloud_tenant_spec.rb

Zombie children were remaining in VMDB when DELETE targeted refresh was triggered on parent entity because Nuage doesn't emit events for underlying children (which get implicitly deleted).
With this commit we tell Rails to always remove all the children in VMDB as well to avoid the zombie thing.

Destroy dependent entities when parent is deleted

---

.babelrc
.gitignore
.npmrc
.postcssrc.yml
package.json

With this commit we provide nothing but configuration files needed for Nuage React Components.
/cc @Hyperkid123 @martinpovonly

Setup React component

---

app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_router.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_router_is_deleted.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_router_is_updated.yml

With this commit we overcome a bug on Nuage side that upon instantiating router template, no events are emitted for subnets.
In other words: when we instantiate template that also contains subnets, MIQ is not explicitly informed that subnets were created, because events are missing. So we play smart: when "router create" event is triggered, we infer all its subnets as well.
NOTE: glitch only appears when we CREATE router. Updating/deleting router properly emits events so we're only fixing this specific case.

Overcome missing event glitch of Nuage server (targeted refresh)

---

app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb

With this commit we add a simple debug log to easily debug targeted refresh if needed. It outpust following to nuage.log:
```
[----] I, [2018-...] DEBUG -- : target: domain - CREATE - Routy - 143e678c-ef2a-4b36-9bad-a6c157ba2038
[----] I, [2018-...] DEBUG -- : target: policygroup - CREATE - PolicyTEMPLATE - 3a037fd0-41b6-4fbf-a080-06ba7d93daa0
[----] I, [2018-...] DEBUG -- : target: domain - DELETE - Routy - 143e678c-ef2a-4b36-9bad-a6c157ba2038
```

Debug log when targeted refresh takes place

---

bin/setup

Core repository no longer contains log folder, which needs to be
created manually.
This commit simply ensures that log folder is present when checking
out manageiq core repository into spec folder.

Add missing log file before running tests

---

config/settings.yml

This will make Nuage events visible in "Monitoring -> Timelines" view.
This pull request depends on https://github.com/ManageIQ/manageiq-ui-classic/pull/4375 and is replacing #80.
@miq-bot add_label wip
/cc @miha-plesko @gberginc

Assign Nuage event types to timeline categories

---

bin/setup

Since https://github.com/ManageIQ/manageiq/pull/17886 has been merged, no work-around is needed anymore in order to run tests. This pull requests simply removes it from the code base.
@miq-bot assign @miha-plesko

Revert "Add missing log file before running tests"

---

app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
app/models/manageiq/providers/nuage/network_manager.rb
app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/no_api_interaction.yml

With this commit we tackle Nuage glitch that event is not triggered. So when subnet template is deleted, also all the subnets that are connected to it are deleted, but no explicit event is triggered for them hence MIQ does not remove them from VMDB.
Solution: we now capture "subnet template was deleted" event and manually remove all subnets linked to subnet template.
To get things even better: MIQ is currently not inventoring subnet templates nor supports anything like this in its schema. Therefore we abuse `cloud_subnet.extra_attributes` to store subnet template ID in it so that we can later know what subnets are linked to which subnet template.

Remove CloudSubnet when corresponding subnet template is deleted

---

app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb
spec/models/manageiq/providers/nuage/network_manager/inventory_parser_spec.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml

There is a known Nuage glitch that some events are not being emitted. With this commit we tackle the one that when zone or zone template are deleted, also all the subnets in it are deleted, but MIQ has no idea about it. So we need to play smart: when recieveing either of
```
nuage_zonetemplate_delete
nuage_zone_delete
```
events, we manually mark also all corresponding subnets for deletion.

Targeted refresh: remove subnet when zone is removed

---

lib/manageiq/providers/nuage/engine.rb

See ManageIQ/manageiq-ui-classic#4496 for primary motivation.

Add plugin display name

---

app/models/manageiq/providers/nuage/inventory/collector/network_manager.rb
app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
app/models/manageiq/providers/nuage/inventory/persister/definitions/network_collections.rb
app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_vm.yml

With this commit we extend inventoring of `NetworkPort::Vm` model to now connect it to a `Vm`. We assume that VM is in VMDB at the time refresh takes place. It will be connected regardless what provider the VM belongs to.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1619544

Cross-provider connect NetworkPort to Vm

---

app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb
app/models/manageiq/providers/nuage/network_manager/network_router.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml

With this commit we perform two things:
- inventoring now fetches relation to parent of the SecurityGroup (can   be either NetworkRouter (L3 domain) or CloudSubnet::L2 (L2 Domain))
- set `:destroy => :dependent` because when parent is deleted, SecurityGroup is always deleted as well

Connect SecurityGroup to NetworkRouter/CloudSubnet

---

app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb

Move ManagerRefresh to InventoryRefresh
Depends on:

Move ManagerRefresh to InventoryRefresh

---

app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
app/models/manageiq/providers/nuage/inventory/persister/definitions/network_collections.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml
spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_vm.yml

Until now we were connecting NetworkPorts to VM by vm.ems_ref, but turns out Nuage vPort actually contains UUID value of the VM which is stored as
```
vm.uid_ems
```
Usecase we're testing it on is for VMware vCenter VM's while other providers (who might actually have the UUID stored in `vm.ems_ref`) are currently not of high priority to Nuage.
With this commit we switch matching from `ems_ref` to `uid_ems`.
Screenshot how vCenter VMs are now cross-connected to Nuage vports (a VM can be connected to more than one vPort):
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1635232

Cross-connect NetworkPorts by `vm.uid_ems`

---

app/models/manageiq/providers/nuage/ansible_crud_mixin.rb
app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb
app/models/manageiq/providers/nuage/network_manager/floating_ip.rb
app/models/manageiq/providers/nuage/network_manager/security_group.rb
spec/models/manageiq/providers/nuage/network_manager/cloud_subnet_spec.rb
spec/models/manageiq/providers/nuage/network_manager/floating_ip_spec.rb
spec/models/manageiq/providers/nuage/network_manager/security_group_spec.rb
spec/spec_helper.rb

With this commit we make sure every Ansible::Runner command is followed by "ansible_raise_for_status" check that raises error when playbook execution errored.
Also, we add playbook logging regardless its execution success/failure, but on debug level. This way we will be able to see playbook outputs in log/nuage.log, when desired.
Screenshot of
```
less -r log/nuage.log
```
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1642472

Raise error when built-in CRUD playbook fails

---

app/models/manageiq/providers/nuage/inventory/persister.rb

The shared_options were duplicated from the base persister

Remove duplicated persister shared_options

---

spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb

So these counts needed to be adjusted to reflect that ems leaf classes have the inheritance set when you use the factory. 
🤷‍♀ 
I can't even actually run specs here at all, because of this:
An error occurred while loading spec_helper.
Failure/Error: require 'qpid_proton'
LoadError:
cannot load such file -- qpid_proton
but it's highly likely that's just me.

Fix spec failures for ems counts

---

.travis.yml

There was a mismatch between matrix and excludes block which caused javascript tests be run two times (which is overkill). Not anymore.
/cc @himdel

Update the excludes block in .travis.yml

---

config/initializers/gettext.rb

There's no need for the plugin to initialize its own catalog anymore.

Remove gettext initializer

---

app/helpers/manageiq/providers/nuage/toolbar_overrides/network_router_center.rb

After ManageIQ/manageiq-ui-classic#5997 `to_json` is not needed and will break the data format.
Related to ManageIQ/manageiq-ui-classic#6289 fix but **not** dependent either way.
Before:
Button `Create L3 Cloud Subnet` doesn't work on click.
After:
Button works as expected.
@miq-bot add_label ivanchuk/no

Remove to_json from toolbar data as it's not needed

---

app/models/manageiq/providers/nuage/manager_mixin.rb

https://github.com/ManageIQ/manageiq/issues/18818

Add params_for_create and verify_credentials

---

app/models/manageiq/providers/nuage/network_manager.rb
config/settings.yml

Remove inventory_object_refresh from settings as part of the effort to remove the old legacy EmsRefresh and save_inventory refresh code.

Remove inventory refresh from settings

---

.gitignore
tools/ci/before_install.sh

We bumped the qpid_proton gem version to 0.30.0 in https://github.com/ManageIQ/manageiq/pull/20016, update the C library to
the same version.

Update the qpid-proton C library version to 0.30.0

---

spec/models/manageiq/providers/nuage/network_manager_spec.rb

This is a minor adjustment to the `ems.ansible_root.to_s` test. I removed the git repo parent directory check since it could actually be anything, and caused failures for me locally since I tend to append my git repos with "-djberg96". Presumably it's only what's beneath it that really matters.

Don't include repo name in ansible root check

---

app/models/manageiq/providers/nuage/network_manager/vsd_client/rest.rb

Within the `ManageIQ::Providers::Nuage::NetworkManager::VsdClient::Rest#request`, which is a wrapper for `RestClient::Request#execute`, any requests with a payload will currently fail.
The problem is that the current code is setting the `:data` option, when in fact rest-client uses a `:payload` option:
https://github.com/rest-client/rest-client/blob/master/lib/restclient/request.rb#L54
https://github.com/rest-client/rest-client/blob/master/lib/restclient/request.rb#L163
Based on my (admittedly vague) recollection from my days writing azure-armrest, even a nil `:payload` will cause problems for requests that don't support them, so that key is only added to the hash of options if the payload is non-nil.
While I was here I also added the `:proxy` option.

Use :payload instead of :data, set :proxy, in Rest class

---

tools/ci/before_install.sh

Instead of passing BUNDLE_WITH=qpid_proton as an env var which isn't able to be generically passed by cross_repo-tests we can use `bundle config with` to set it.
This allows cross_repo to just call `tools/ci/before_install.sh` as normal and enable the bundler group without any repo specifics or env var passthroughs.

Use before_install to setup bundle_with qpid_proton

---

spec/models/manageiq/providers/nuage/vsd_client/vsd_client_spec.rb

The current `VsdClient` specs have a couple issues. First is that the specs fail with strict partials enabled. The issue is that the constructor requires 3 arguments, so I've added some placeholder values.
Second, the way the specs are currently written stub out the `:initialize` method. This seems to make rspec upset, and it spews lots of warnings. See https://github.com/ManageIQ/manageiq-providers-nuage/issues/207 for more details.
Note that I had to fully qualify the `Rest` class, or rspec got confused. I'm not sure if there's a trick to seeing nested classes with rspec, but fully qualifying it is clearer anyway IMO.
Fixes https://github.com/ManageIQ/manageiq-providers-nuage/issues/207

Cleanup spec warnings, fix strict partial failures

---

app/models/manageiq/providers/nuage/manager_mixin.rb
app/models/manageiq/providers/nuage/network_manager.rb

In order to bypass [`belongs_to`])(https://github.com/ManageIQ/manageiq/blob/master/app/models/manageiq/providers/network_manager.rb#L37-L40) that's defined globally for all network providers, I had to implement `ManageIQ::Providers::Nuage::NetworkManager.supported_for_create?` to return `true`. It can be removed after the manager link is not set globally for all managers, but only for those which really need it.
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
cc @h-kataria

Adjusted DDF schema for provider creation with updated validation

---

app/models/manageiq/providers/nuage/network_manager/event_catcher/runner.rb
spec/models/manageiq/providers/nuage/network_manager/event_catcher/runner_spec.rb

Without setting the monitor_running concurrent event the main
event_catcher worker thread doesn't ever leave the do_before_work_loop
which means it can't be shutdown cleanly until the first event is
raised.

Set the monitor_running event to unblock the main thread

---

spec/helpers/manageiq/providers/nuage/toolbar_overrides/network_router_center_spec.rb

https://github.com/ManageIQ/manageiq-ui-classic/pull/7247 changed toolbar group ids to also include the class name,
updating the test to do the same.
Should fix https://travis-ci.com/github/ManageIQ/manageiq-providers-nuage/jobs/369417141#L2397-L2413

Fix toolbar specs after ui7247

---

app/models/manageiq/providers/nuage/network_manager.rb

Needed for: https://github.com/ManageIQ/manageiq/pull/20345

Don't delegate queue_name to parent_manager

---

app/javascript/components/create-nuage-cloud-subnet-form.jsx

Missed an extra `)` :see_no_evil:

Fixed JS syntax error in the create cloud subnet form

---

app/models/manageiq/providers/nuage/manager_mixin.rb

The default behavior for the `async-credentials` component is [changing to be optional](https://github.com/ManageIQ/manageiq-ui-classic/pull/7347), so it has to be explicitly marked as required here.

Make the default credentials required in the provider DDF

---

app/models/manageiq/providers/nuage/manager_mixin.rb

Because carbon has four different dropdowns, the DDF schemas need to have explicit initialValue or includeEmpty settings in order to make the form validation work.
@miq-bot assign @agrare

Adjust empty/initial values for select fields in DDF schemas

---

app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb

Changes `ems.network` to `ems.cloud_network` to ensure the Network field correctly displays available networks

Modified Network Field of Cloud Subnet Form

---

app/models/manageiq/providers/nuage/network_manager/cloud_tenant.rb

```
DEPRECATION WARNING: `Module#parent` has been renamed to `module_parent`. `parent` is deprecated and will be removed in Rails 6.1. (called from l3_cloud_subnets at /home/travis/build/ManageIQ/manageiq-providers-nuage/app/models/manageiq/providers/nuage/network_manager/cloud_tenant.rb:9)
DEPRECATION WARNING: `Module#parent` has been renamed to `module_parent`. `parent` is deprecated and will be removed in Rails 6.1. (called from l2_cloud_subnets at /home/travis/build/ManageIQ/manageiq-providers-nuage/app/models/manageiq/providers/nuage/network_manager/cloud_tenant.rb:13)
```

Fix deprecated `Module#parent` in CloudTenant

---

app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb

- `delete_cloud_subnet_queue` was removed and added to core
Depends on:

Refactor delete subnet queue

---

app/models/manageiq/providers/nuage/network_manager.rb

- `create_cloud_subnet_queue` method lives in the provider code but it is unnecessary and can be moved to core
Depends on:

Refactor create cloud subnet queue

---

app/models/manageiq/providers/nuage/inventory/persister/definitions/network_collections.rb

The handling of the "parent" manager has been added as a feature of the `add_TYPE_collection` methods in core.

Use standard persister builder methods from core

---

bin/before_install

The Ubuntu Kinetic 22.10 release has reached end-of-life and the repository files have been removed from mirrors.
Ubuntu Lunar 23.04 has the same version of libqpid-proton11
Related: https://github.com/ManageIQ/manageiq-providers-openstack/pull/861

Ubuntu Kinetic has been removed, replace with Lunar

---

content/ansible_runner/create-subnet.yml
content/ansible_runner/remove-floating-ip.yml
content/ansible_runner/remove-policy-group.yml
content/ansible_runner/remove-subnet.yml
content/ansible_runner/roles/requirements.yml

The GitHub repos have moved from xlab_si to xlab-si which is causing the
old galaxy roles links to fail with a 404 error.

Fix xlab-si galaxy roles pointing to invalid repository URL

---

app/models/manageiq/providers/nuage/network_manager/event_catcher/messaging_handler.rb
lib/manageiq/providers/nuage/engine.rb
spec/models/manageiq/providers/nuage/network_manager/event_catcher/messaging_handler_spec.rb
spec/models/manageiq/providers/nuage/network_manager/event_catcher/runner_spec.rb
spec/models/manageiq/providers/nuage/network_manager/event_catcher/stream_spec.rb
spec/models/manageiq/providers/nuage/network_manager_spec.rb
spec/spec_helper.rb

* We're not setup to autoload the library so we need to manually require the gem before using it.
* Some environments don't have qpid_proton installed so explicitly tell zeitwerk to not autoload or eager load the messaging handler
* Mark specs requiring qpid_proton and exclude them if not available
Related change that should be merged together: https://github.com/ManageIQ/manageiq/pull/22763

Require the gem defining the constant we're subclassing

---

app/models/manageiq/providers/nuage/inventory.rb
app/models/manageiq/providers/nuage/inventory/collector.rb
app/models/manageiq/providers/nuage/inventory/parser.rb
app/models/manageiq/providers/nuage/inventory/persister.rb
app/models/manageiq/providers/nuage/network_manager.rb
app/models/manageiq/providers/nuage/network_manager/event_catcher.rb
app/models/manageiq/providers/nuage/network_manager/refresh_worker.rb

Zeitwerk completely removes the need for these methods. See also: https://github.com/ManageIQ/manageiq/pull/22854

Drop require_nested
