CHANGELOG.md
Further edits to standardize the changelogs
=> Update with standard format

app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
With this commit we refactor client so that it doesn't produce code climate errors about repeated code anymore. Also we add a TODO since such hard-coded headers seem wrong.
@miq-bot add_label cleanup
@miq-bot assign @Ladas
=> Extract vsd_client header into a function

bin/qpid_install.sh
This will remove swig from qpid_install.sh.
=> Remove swig from travis

spec/models/manageiq/providers/nuage/vsd_client/vcr_specs/vsd_client_spec.rb, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/domain.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/domains.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/domains_for_enterprise_id.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/enterprise.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/enterprises.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/login.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/policy_group.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/policy_groups.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/policy_groups_for_domain.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/subnet.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/subnets.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/subnets_for_domain.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/vms.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/wrong_pass.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/wrong_user.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/zone.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/zones.yml
Contains some basic test cases for the vsd client. Tests
ok responses for common parameters, expects errors on
wrong username and password.
=> Rspec test for vsd_client.rb

spec/models/manageiq/providers/nuage/network_manager/event_catcher/alarm_delete.json, spec/models/manageiq/providers/nuage/network_manager/event_catcher_spec.rb, spec/models/manageiq/providers/nuage/network_manager/event_parser_spec.rb, spec/models/manageiq/providers/nuage/network_manager_spec.rb, spec/spec_helper.rb
With this patch we are adding specs to test the Nuage network manager,
event catcher and event parser.
=> Add Nuage manager and event catcher specs

bin/qpid_install.sh
Bump qpid-proton version to 0.18.1
Addresses https://github.com/ManageIQ/manageiq-providers-nuage/issues/42
/cc @gberginc 
/cc @miha-plesko
=> Bump qpid-proton version to 0.18.1

app/models/manageiq/providers/nuage/network_manager/refresher.rb
Remove useless EmsRefresherMixin removed in https://github.com/ManageIQ/manageiq/pull/17472
=> Remove useless EmsRefresherMixin

app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb, app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb, app/models/manageiq/providers/nuage/network_manager/vsd_client.rb, spec/factories/floating_ip.rb, spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/floating_ip.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/floating_ip_is_deleted.yml, spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/floating_ip_is_updated.yml
=> Targeted refresh for FloatingIp

app/models/manageiq/providers/nuage/ansible_crud_mixin.rb, app/models/manageiq/providers/nuage/network_manager.rb, app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb, content_tmp/ansible/create-subnet.yml, content_tmp/ansible/roles/requirements.yml, spec/models/manageiq/providers/nuage/network_manager/cloud_subnet_spec.rb
With this commit we provide backend logic for CloudSubnet:L3 creation as well as corresponding playbook. Playbook first creates Zone on Nuage server (if not exist) and then adds desired Subnet to it.
=> Implement CREATE operation for CloudSubnet

app/models/manageiq/providers/nuage/inventory/collector.rb, app/models/manageiq/providers/nuage/inventory/collector/network_manager.rb, app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
With this commit we cleanup refresher code. There are two pieces of it:
- targeted refresh collector: remove a bunch of unused functions
- full refresh collector: reduce memoization where not needed
All the unit tests still stand.
=> Cleanup refresher code

app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
With this commit we fix bug that caused inventoring crash if Nuage server contains at least one SecurityGroup that is connected to L2 domain (as opposed to L3 domains, as implementation assumes).
Problem was that parentID on security group can refer either to L2 domain or L3 domain, but we assumed L3 domain.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1626219
=> [GAPRINDASHVILI] Prevent crash upon inventoring SecurityGroups

CHANGELOG.md
=> [Changelog] Update for Hammer Beta-1

CHANGELOG.md
=> [Changelog] Update for Sprint 98 and H-B1

spec/factories/cloud_network.rb, spec/factories/cloud_subnet.rb, spec/factories/cloud_tenant.rb, spec/factories/ext_management_system.rb, spec/factories/floating_ip.rb, spec/factories/network_port.rb, spec/factories/network_router.rb, spec/factories/security_group.rb, spec/models/manageiq/providers/nuage/network_manager/cloud_subnet_spec.rb, spec/models/manageiq/providers/nuage/network_manager/cloud_tenant_spec.rb, spec/models/manageiq/providers/nuage/network_manager/event_catcher/runner_spec.rb, spec/models/manageiq/providers/nuage/network_manager/event_catcher_spec.rb, spec/models/manageiq/providers/nuage/network_manager/event_parser_spec.rb, spec/models/manageiq/providers/nuage/network_manager/event_target_parser_spec.rb, spec/models/manageiq/providers/nuage/network_manager/floating_ip_spec.rb, spec/models/manageiq/providers/nuage/network_manager/security_group_spec.rb, spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb, spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb, spec/models/manageiq/providers/nuage/network_manager_spec.rb
This PR is a followup to ManageIQ/manageiq#18279 where we're updating FactoryGirl to FactoryBot.
=> Change FactoryGirl to FactoryBot

lib/manageiq/providers/nuage/engine.rb
Change plugin common methods to class methods
=> Change plugin common methods to class methods

spec/models/manageiq/providers/nuage/network_manager/event_parser_spec.rb
🤷‍♀ 
Sorry Adam but I think this one's gotta go since I don't even know why you would...
=> Fix specs failing cause we're using the same guid :rage:

app/models/manageiq/providers/nuage/network_manager/event_catcher.rb, app/models/manageiq/providers/nuage/network_manager/refresh_worker.rb
requires https://github.com/ManageIQ/manageiq/pull/19516
=> Rely on the default implementation of .ems_class

app/models/manageiq/providers/nuage/network_manager.rb, app/models/manageiq/providers/nuage/network_manager/refresher.rb, spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb, spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
only amazon's left to go now 🎉
=> remove what's left of inventory object refresh

manageiq-providers-nuage.gemspec
https://hakiri.io/github/ManageIQ/manageiq-providers-nuage/master/30b4fce7f44260b2a593ebe939b5af5f021d7748/warnings?name=Information+Disclosure
=> Bump the excon gem to fix security issue

tools/ci/before_install.sh
Follow up to: https://github.com/ManageIQ/manageiq-providers-nuage/pull/201#discussion_r405742793
Just needs a rebase after https://github.com/ManageIQ/manageiq-providers-nuage/pull/203
=> Use pushd/popd instead of cd at the end of the script

app/javascript/components/create-nuage-cloud-subnet-form.jsx, app/javascript/components/create-nuage-cloud-subnet-form.schema.js, app/models/manageiq/providers/nuage/manager_mixin.rb
https://github.com/ManageIQ/manageiq-ui-classic/issues/7277
=> Update DDF schema to version 2

.codeclimate.yml, .gitignore, .rubocop.yml, .rubocop_cc.yml, .travis.yml, README.md, Rakefile, bin/ci/after_script, lib/manageiq/providers/nuage/engine.rb, lib/tasks/README.md, lib/tasks_private/spec.rake, lib/tasks_private/yarn.rake, manageiq-providers-nuage.gemspec, spec/spec_helper.rb, spec/support/playbook_helper.rb
=> Plugin Generator Updates

.codeclimate.yml, .rubocop.yml, .rubocop_cc.yml, manageiq-providers-nuage.gemspec
Depends On: ManageIQ/miq_bot#506
=> Use manageiq-style

lib/manageiq/providers/nuage/engine.rb
Move logger initialization and configuration into plugins
=> Move logger initialization and configuration into plugins

app/models/manageiq/providers/nuage/network_manager.rb, app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/6861
=> Implemented DDF for cloud subnets and added support mixin call

systemd/manageiq-providers-nuage_network_manager_event_catcher@.service, systemd/manageiq-providers-nuage_network_manager_refresh@.service
part of https://github.com/ManageIQ/manageiq-rpm_build/pull/157
using manageiq properties and still running as root (but very close to switching over to manageiq user)
=> add properties files to systemd

systemd/manageiq-providers-nuage_network_manager_event_catcher@.service, systemd/manageiq-providers-nuage_network_manager_refresh@.service
=> run services as manageiq user

app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
=> Move add_target and references to core collector

app/models/manageiq/providers/nuage/network_manager.rb
part of https://github.com/ManageIQ/manageiq/pull/21573
=> converting supported_for_create to supports :create

app/models/manageiq/providers/nuage/inventory/persister/definitions/network_collections.rb
Required for: https://github.com/ManageIQ/manageiq/pull/21597
=> Skip STI for referenced VMs

app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb, app/models/manageiq/providers/nuage/inventory/persister/definitions/network_collections.rb
=> Use cross_link_vms collection from core

app/models/manageiq/providers/nuage/manager_mixin.rb
Continuing to remove uneeded memoization, with some additional translation fixes. 
@miq-bot add-label bug
@miq-bot add-label najdorf/yes?
@miq-bot assign @agrare
=> Removing Memoization

app/models/manageiq/providers/nuage/manager_mixin.rb
https://github.com/ManageIQ/manageiq/issues/22845
=> Add zone_id to provider validationDependencies

app/models/manageiq/providers/nuage/network_manager/vsd_client.rb, app/models/manageiq/providers/nuage/network_manager/vsd_client/rest.rb
=> Avoid loading client libraries at code load time for domain classes.

.github/workflows/ci.yaml, bin/before_install
=> Use ubuntu-24.04 to fix libqpid-proton11 install

.github/workflows/ci.yaml
Related https://github.com/ManageIQ/manageiq-providers-openstack/pull/902
Follow-up: https://github.com/ManageIQ/manageiq-providers-nuage/pull/326
=> Use ubuntu-latest now that it is 24.04

.gitignore, config/secrets.defaults.yml, lib/manageiq/providers/nuage/engine.rb, spec/config/secrets.defaults.yml, spec/factories/ext_management_system.rb, spec/models/manageiq/providers/nuage/vsd_client/vcr_specs/vsd_client_spec.rb, spec/spec_helper.rb
=> Switch to use VcrSecrets helper from core

lib/manageiq/providers/nuage/engine.rb
Depends indirectly on: https://github.com/ManageIQ/manageiq/pull/23509
=> Drop to_s on engine paths
